/**
 * Experienced User Dashboard Component
 *
 * Full-featured dashboard for users with 3+ projects or 7+ days of usage.
 * Shows all stats, recent projects, quick actions, and advanced features.
 * Implements progressive disclosure (Miller's Law).
 */

'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { TemplateDialog } from '@/components/dashboard/template-dialog'
import { QuickActions } from '@/components/dashboard/quick-actions'
import { StatCard } from '@/components/dashboard/stat-card'
import { EmptyState } from '@/components/dashboard/empty-state'
import { ArrowUpRight, FileText, PenSquare, Sparkles, HelpCircle } from 'lucide-react'

interface Project {
  id: string
  name: string
  type: string
  created_at: string
}

interface ExperiencedDashboardProps {
  projects: Project[]
  stats: {
    projectCount: number
    documentCount: number
    totalWordsGenerated: number
  }
}

export function ExperiencedDashboard({ projects, stats }: ExperiencedDashboardProps) {
  const [showTemplateDialog, setShowTemplateDialog] = useState(false)

  return (
    <div className="space-y-12">
      {/* Hero Section - Full Featured */}
      <section className="flex flex-col gap-6 rounded-2xl bg-gradient-to-br from-primary/10 via-background to-accent/5 p-10 shadow-lg md:flex-row md:items-center md:justify-between">
        <div className="space-y-5">
          <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-wide text-primary">
            <Sparkles className="h-4 w-4" />
            Workspace Overview
          </div>
          <div className="space-y-3">
            <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
              Welcome back, storyteller.
            </h1>
            <p className="max-w-xl text-base text-muted-foreground sm:text-lg">
              Keep your narratives, characters, and outlines aligned. Here&apos;s what&apos;s happening across your workspace today.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-3 pt-2">
            <Button
              size="lg"
              className="h-12 px-6 text-base font-semibold shadow-md"
              onClick={() => setShowTemplateDialog(true)}
            >
              <PenSquare className="mr-2 h-5 w-5" />
              New from Template
            </Button>
            <Button variant="outline" size="lg" className="h-12 px-6" asChild>
              <Link href="/dashboard/projects">
                View Projects
                <ArrowUpRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>
        <div className="flex flex-col gap-3 rounded-2xl border border-border/50 bg-card/50 p-5 shadow-sm">
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground/80">
            Recent milestones
          </p>
          <ul className="space-y-2.5 text-sm text-muted-foreground">
            <li className="flex items-center justify-between">
              <span>Projects created</span>
              <Badge variant="outline" className="text-xs text-primary">
                {stats.projectCount}
              </Badge>
            </li>
            <li className="flex items-center justify-between">
              <span>Active documents</span>
              <Badge variant="outline" className="text-xs">
                {stats.documentCount}
              </Badge>
            </li>
            <li className="flex items-center justify-between">
              <span className="flex items-center gap-1.5">
                AI words generated
                <TooltipProvider delayDuration={300}>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <button
                        type="button"
                        className="inline-flex text-muted-foreground/60 transition hover:text-muted-foreground"
                        aria-label="Information about AI words generated"
                      >
                        <HelpCircle className="h-3 w-3" />
                      </button>
                    </TooltipTrigger>
                    <TooltipContent side="top" className="max-w-xs">
                      <p className="text-xs">
                        Total words generated by Ottowrite&apos;s AI assistant across all documents,
                        including outlines, character descriptions, dialogue suggestions, and prose
                      </p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </span>
              <Badge variant="outline" className="text-xs">
                {stats.totalWordsGenerated.toLocaleString()}
              </Badge>
            </li>
          </ul>
        </div>
      </section>

      {/* Stats - Full 3 Cards */}
      <section className="grid gap-4 md:grid-cols-3">
        <StatCard
          label="Projects"
          value={stats.projectCount}
          helper="Across all genres"
          icon={<PenSquare className="h-6 w-6" />}
          delta={{ value: '+2 this month', positive: true }}
          tone="primary"
          priority="high"
          tooltip="Total number of writing projects you've created across all genres (novels, screenplays, series, plays, and short stories)"
        />
        <StatCard
          label="Documents"
          value={stats.documentCount}
          helper="Works in progress"
          icon={<FileText className="h-5 w-5" />}
          tone="secondary"
          tooltip="Active documents across all your projects, including chapters, scenes, outlines, and character profiles"
        />
        <StatCard
          label="AI words"
          value={stats.totalWordsGenerated.toLocaleString()}
          helper="Saved via Ottowrite"
          icon={<Sparkles className="h-5 w-5" />}
          tone="accent"
          tooltip="Total words generated by Ottowrite's AI assistant across all documents, including outlines, character descriptions, dialogue suggestions, and prose"
        />
      </section>

      {/* Recent Projects */}
      <section className="space-y-6">
        <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <h2 className="text-2xl font-semibold">Recent projects</h2>
            <p className="text-sm text-muted-foreground">
              Resume where you left off or spin up something new.
            </p>
          </div>
          <Button variant="ghost" asChild>
            <Link href="/dashboard/projects" className="flex items-center gap-2 text-sm font-medium">
              View all projects
              <ArrowUpRight className="h-4 w-4" />
            </Link>
          </Button>
        </div>
        {projects.length > 0 ? (
          <div className="grid gap-4 md:grid-cols-2">
            {projects.map((project) => (
              <div
                key={project.id}
                className="rounded-2xl border bg-card/80 p-6 shadow-card transition hover:shadow-lg"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-semibold text-foreground">{project.name}</h3>
                    <Badge variant="muted" className="capitalize">
                      {project.type.replace('_', ' ')}
                    </Badge>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Last updated {new Date(project.created_at).toLocaleDateString()}
                  </p>
                </div>
                <div className="mt-5 flex items-center gap-3">
                  <Button asChild>
                    <Link href={`/dashboard/projects/${project.id}`}>Open project</Link>
                  </Button>
                  <Button variant="outline" asChild>
                    <Link href={`/dashboard/projects/${project.id}/characters`}>Characters</Link>
                  </Button>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <EmptyState
            icon={PenSquare}
            title="No projects yet"
            description="Start your first project to unlock AI-assisted outlining, character management, and scene planning."
            action={{ label: 'Create project', href: '/dashboard/projects?new=true' }}
            secondaryAction={{ label: 'Browse templates', href: '/dashboard/projects' }}
          />
        )}
      </section>

      {/* Quick Actions */}
      <section className="space-y-6">
        <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <h2 className="text-2xl font-semibold">Quick actions</h2>
            <p className="text-sm text-muted-foreground">
              Accelerate your writing workflow with these shortcuts.
            </p>
          </div>
        </div>
        <QuickActions />
      </section>

      <TemplateDialog open={showTemplateDialog} onOpenChange={setShowTemplateDialog} />
    </div>
  )
}
