import Link from 'next/link'
import { Button } from '@/components/ui/button'

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <Link href="/" className="text-2xl font-bold">
            Ottowrite
          </Link>
          <div className="flex gap-4">
            <Link href="/auth/login">
              <Button variant="ghost">Login</Button>
            </Link>
            <Link href="/auth/signup">
              <Button>Sign Up</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Content */}
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last Updated: January 22, 2025</p>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Ottowrite (&quot;the Service&quot;), you agree to be bound by these Terms of Service
              (&quot;Terms&quot;). If you do not agree to these Terms, you may not access or use the Service.
            </p>
            <p>
              These Terms constitute a legally binding agreement between you and Ottowrite (&quot;we&quot;, &quot;us&quot;, or
              &quot;our&quot;). We reserve the right to modify these Terms at any time. Continued use of the Service after
              changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
            <p>
              Ottowrite is an AI-powered writing platform that provides tools for prose and screenplay creation,
              editing, and collaboration. The Service includes:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI-assisted writing and editing features</li>
              <li>Document management and version control</li>
              <li>Collaboration tools for teams</li>
              <li>Export capabilities in multiple formats</li>
              <li>Character, plot, and world-building tools</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
            <h3 className="text-xl font-semibold mb-3">3.1 Account Registration</h3>
            <p>
              To use certain features of the Service, you must create an account. You agree to provide accurate,
              current, and complete information during registration and to update such information to keep it accurate.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-4">3.2 Account Security</h3>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all
              activities that occur under your account. You agree to notify us immediately of any unauthorized use of
              your account.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-4">3.3 Account Termination</h3>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of these Terms or
              for any other reason at our sole discretion.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">4. User Content</h2>
            <h3 className="text-xl font-semibold mb-3">4.1 Ownership</h3>
            <p>
              You retain all ownership rights to the content you create using the Service (&quot;User Content&quot;). By using
              the Service, you grant us a limited, worldwide, non-exclusive license to use, store, and process your
              User Content solely for the purpose of providing and improving the Service.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-4">4.2 AI-Generated Content</h3>
            <p>
              Content generated by our AI tools is provided to you under a non-exclusive license. You are responsible
              for reviewing and validating all AI-generated content for accuracy, appropriateness, and compliance with
              applicable laws before use or publication.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-4">4.3 Responsibility for Content</h3>
            <p>
              You are solely responsible for your User Content and the consequences of posting or publishing it. You
              represent and warrant that you own or have the necessary rights to use and authorize us to use all User
              Content as described in these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon the intellectual property rights of others</li>
              <li>Generate, store, or share illegal, harmful, or offensive content</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the Service or servers</li>
              <li>Use automated systems to access the Service without authorization</li>
              <li>Resell or redistribute the Service without authorization</li>
            </ul>
            <p className="mt-4">
              See our <Link href="/acceptable-use" className="text-primary hover:underline">Acceptable Use Policy</Link> for
              more details.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">6. Subscription and Payment</h2>
            <h3 className="text-xl font-semibold mb-3">6.1 Pricing</h3>
            <p>
              We offer both free and paid subscription plans. Pricing details are available on our{' '}
              <Link href="/pricing" className="text-primary hover:underline">Pricing page</Link>. We reserve the right to
              change our pricing at any time with 30 days notice to existing subscribers.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-4">6.2 Billing</h3>
            <p>
              Paid subscriptions are billed on a recurring basis according to your selected plan. By subscribing, you
              authorize us to charge your payment method on each billing cycle.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-4">6.3 Refunds</h3>
            <p>
              We offer a 7-day money-back guarantee on all paid plans. See our{' '}
              <Link href="/refund-policy" className="text-primary hover:underline">Refund Policy</Link> for details.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">7. Intellectual Property</h2>
            <p>
              The Service, including all software, text, graphics, logos, and other content (excluding User Content),
              is owned by Ottowrite and protected by copyright, trademark, and other intellectual property laws. You
              may not copy, modify, distribute, or create derivative works based on the Service without our express
              written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">8. Privacy</h2>
            <p>
              Your use of the Service is also governed by our{' '}
              <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>, which describes how we
              collect, use, and protect your personal information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">9. Disclaimers</h2>
            <h3 className="text-xl font-semibold mb-3">9.1 Service Availability</h3>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
              IMPLIED. We do not guarantee that the Service will be uninterrupted, secure, or error-free.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-4">9.2 AI Accuracy</h3>
            <p>
              While we strive to provide accurate and helpful AI-generated content, we do not guarantee the accuracy,
              completeness, or reliability of any AI-generated content. You use AI-generated content at your own risk.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-4">9.3 Third-Party Services</h3>
            <p>
              The Service may integrate with or link to third-party services. We are not responsible for the content,
              accuracy, or practices of third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">10. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, OTTOWRITE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED
              DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
            </p>
            <p className="mt-4">
              IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL DAMAGES EXCEED THE AMOUNT YOU PAID US IN THE TWELVE
              (12) MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">11. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Ottowrite, its officers, directors, employees, and agents from
              any claims, damages, losses, liabilities, and expenses (including legal fees) arising out of or related
              to your use of the Service, your User Content, or your violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the United States and the
              State of Delaware, without regard to conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">13. Dispute Resolution</h2>
            <p>
              Any disputes arising out of or relating to these Terms or the Service shall be resolved through binding
              arbitration in accordance with the rules of the American Arbitration Association, except that either
              party may seek injunctive relief in court for intellectual property disputes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">14. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify you of material changes by email
              or through the Service. Your continued use of the Service after such notification constitutes acceptance
              of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4">15. Contact Information</h2>
            <p>
              If you have questions about these Terms, please contact us at:
            </p>
            <ul className="list-none space-y-2 mt-4">
              <li>
                Email:{' '}
                <a href="mailto:legal@ottowrite.app" className="text-primary hover:underline">
                  legal@ottowrite.app
                </a>
              </li>
              <li>
                Contact Form:{' '}
                <Link href="/contact" className="text-primary hover:underline">
                  ottowrite.app/contact
                </Link>
              </li>
            </ul>
          </section>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t mt-16">
        <div className="container mx-auto px-4 py-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4 text-sm text-muted-foreground">
            <p>&copy; 2025 Ottowrite. All rights reserved.</p>
            <div className="flex gap-6">
              <Link href="/privacy" className="hover:text-foreground">
                Privacy Policy
              </Link>
              <Link href="/terms" className="hover:text-foreground">
                Terms of Service
              </Link>
              <Link href="/contact" className="hover:text-foreground">
                Contact
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
