-- MANUSCRIPT SUBMISSIONS - SEED DATA
-- Sample verified partners for testing
-- This file can be run manually or in development environments

-- Note: In production, partners will be added through the partner verification system

INSERT INTO public.submission_partners (
    id,
    name,
    type,
    company,
    email,
    website,
    verified,
    verification_date,
    aar_member,
    genres,
    accepting_submissions,
    submission_guidelines,
    response_time_days,
    bio,
    status
) VALUES
(
    '00000000-0000-0000-0000-000000000001',
    'Sarah Johnson',
    'agent',
    'Johnson Literary Agency',
    'sarah@johnsonliterary.com',
    'https://johnsonliterary.com',
    true,
    NOW(),
    true,
    ARRAY['fiction', 'literary', 'thriller', 'mystery'],
    true,
    'Please submit query letter, synopsis (1-2 pages), and first 10 pages. No attachments.',
    14,
    'Sarah Johnson has been a literary agent for over 15 years, representing award-winning authors in fiction and literary works. AAR member since 2010.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000002',
    'Michael Chen',
    'agent',
    'Chen & Associates',
    'michael@chenassociates.com',
    'https://chenassociates.com',
    true,
    NOW(),
    true,
    ARRAY['science_fiction', 'fantasy', 'young_adult'],
    true,
    'Query letter and first 3 chapters (max 50 pages). Responds to all queries within 30 days.',
    30,
    'Michael Chen specializes in science fiction and fantasy. He represents several NYT bestselling authors in the SFF space.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000003',
    'Emily Rodriguez',
    'agent',
    'The Rodriguez Agency',
    'emily@rodriguezagency.com',
    'https://rodriguezagency.com',
    true,
    NOW(),
    true,
    ARRAY['romance', 'contemporary', 'womens_fiction'],
    true,
    'Query letter, 2-page synopsis, and first 50 pages. Email submissions only.',
    21,
    'Emily Rodriguez represents commercial fiction with a focus on romance and women''s fiction. AAR member.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000004',
    'David Kim',
    'publisher',
    'Indie Press Publishing',
    'submissions@indiepress.com',
    'https://indiepress.com',
    true,
    NOW(),
    false,
    ARRAY['literary', 'memoir', 'non_fiction'],
    true,
    'Complete manuscript required. Include cover letter and author bio. Response time: 60-90 days.',
    75,
    'Independent publisher focusing on literary fiction, memoir, and creative non-fiction. Published over 200 titles.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000005',
    'Jessica Martinez',
    'agent',
    'Martinez Literary Management',
    'jessica@martinezliterary.com',
    'https://martinezliterary.com',
    true,
    NOW(),
    true,
    ARRAY['thriller', 'suspense', 'crime', 'mystery'],
    true,
    'Query with first 10 pages in the body of the email. No attachments in initial submission.',
    10,
    'Jessica Martinez specializes in thrillers and crime fiction. She has 12 years of experience and represents multiple bestselling thriller authors.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000006',
    'Robert Taylor',
    'agent',
    'Taylor & Partners',
    'robert@taylorpartners.com',
    'https://taylorpartners.com',
    true,
    NOW(),
    true,
    ARRAY['historical', 'literary', 'biography'],
    true,
    'Query letter and synopsis only. Sample pages by request. Responds within 6 weeks.',
    42,
    'Robert Taylor has been in publishing for 25 years, with particular interest in historical fiction and literary works.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000007',
    'Amanda Lee',
    'agent',
    'The Lee Agency',
    'amanda@leeagency.com',
    'https://leeagency.com',
    true,
    NOW(),
    false,
    ARRAY['young_adult', 'middle_grade', 'childrens'],
    true,
    'Query letter with first 5 pages. For picture books, send complete manuscript.',
    28,
    'Amanda Lee represents children''s and young adult literature. She has launched several debut authors to commercial success.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000008',
    'Christopher Brown',
    'publisher',
    'Brown Publishing House',
    'submissions@brownpublishing.com',
    'https://brownpublishing.com',
    true,
    NOW(),
    false,
    ARRAY['business', 'self_help', 'non_fiction'],
    true,
    'Book proposal required (overview, market analysis, chapter outline, sample chapters). No fiction.',
    60,
    'Established publisher of business and self-help books. Focuses on practical, actionable content.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000009',
    'Lisa Wang',
    'agent',
    'Wang Literary Services',
    'lisa@wangliterary.com',
    'https://wangliterary.com',
    true,
    NOW(),
    true,
    ARRAY['horror', 'dark_fantasy', 'thriller'],
    true,
    'Query letter with first chapter. Particularly interested in diverse voices and unique perspectives.',
    17,
    'Lisa Wang represents horror, dark fantasy, and psychological thrillers. Known for championing debut authors.',
    'active'
),
(
    '00000000-0000-0000-0000-000000000010',
    'Thomas Anderson',
    'agent',
    'Anderson & Smith Literary',
    'thomas@andersonsmith.com',
    'https://andersonsmith.com',
    true,
    NOW(),
    true,
    ARRAY['literary', 'upmarket', 'book_club'],
    false,
    'Currently closed to submissions. Will reopen in Spring 2025.',
    null,
    'Thomas Anderson represents literary and upmarket fiction with book club appeal. Temporarily closed to queries.',
    'active'
);

-- Update partner stats (these would normally be calculated from actual submissions)
UPDATE public.submission_partners SET
    total_submissions = FLOOR(RANDOM() * 100 + 50),
    total_accepted = FLOOR(RANDOM() * 10 + 2),
    total_rejected = FLOOR(RANDOM() * 40 + 10)
WHERE verified = true;

-- Acceptance rates will be auto-calculated by trigger
